name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'

    - name: Install dependencies
      run: flutter pub get

    - name: Build app
      run: flutter build windows --release
      if: matrix.os == 'windows-latest'

    - name: Build macOS app
      run: flutter build linux --release
      if: matrix.os == 'ubuntu-latest'
      
    - name: Build macOS app
      run: flutter build macos --release
      if: matrix.os == 'macos-latest'

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          Automated release generated by GitHub Actions.
        draft: false
        prerelease: false

    - name: Upload app
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ format('{0}/{1}', github.workspace, env.asset_path[runner.os]) }}
        asset_name: your_app_{{ contains(matrix.os, 'macos-latest') && 'macos.zip' || contains(matrix.os, 'windows-latest') && 'windows.zip' || 'linux.zip' }}
        asset_content_type: application/zip
